name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: Build DMG
        run: npm run dist
      
      - name: List dist folder contents (debug)
        run: ls -la dist
      
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-dmg
          path: dist/*.dmg
